#!/bin/bash
for i in {1..20}; do 
	cat -e $i.txt
done
cat -e 15bytes
cat -e 15bytes.txt
echo ""
echo "==================="
cat -e 31bytes
cat -e 31bytes.txt
echo ""
echo "==================="
md5sum m m.c
diff m m.c
echo "========================"
md5sum grumpycat grumpycat.jpeg
diff grumpycat grumpycat.jpeg
echo "========================"
md5sum ex_data2 ex_data2.c
diff ex_data2 ex_data2.c
echo "========================"
