#!/bin/bash

if [[ "$#" -eq 1 ]]; then
	echo "Creating simple directory structure"
	wget https://raw.githubusercontent.com/openssl/openssl/master/crypto/evp/encode.c
	wget https://ianxaunliu-johnston.com/holberton/img/header_bkg_image-small.png
	echo "123456789abdef" >> 15bytes.txt
	echo "0123456789abdef" >> 16bytes.txt
	echo "0123456789abdef123456789abcdef" >> 31bytes.txt
	echo "0123456789abdef0123456789abcdef" >> 32bytes.txt
	exit
fi
mkdir TESTS
pushd TESTS >> /dev/null 2>&1
echo "#########################"
echo "Regular Files"
echo "#########################"
echo "real content"
wget -q https://raw.githubusercontent.com/openssl/openssl/master/crypto/evp/encode.c
wget -q https://ianxaunliu-johnston.com/holberton/img/header_bkg_image-small.png
echo "Creating a 100M file full of random bytes"
dd if=/dev/urandom of=large_file.html bs=104857601 count=1
echo "abcdefghijklmnopqrstuvwxyz1234567890" >> ignored_file
echo -ne '#include <stdio.h>\nint main(int ac, char *av[])\n{\nint i;\nfor (i = 0; i < atoi(av[1]); i++)\nputchar(i + "a");\nputchar("\\n");\nreturn(0);\n}\n' > t.c
sed -i "s/\"/'/g" t.c
gcc t.c -o specific_byte_sizes
echo "Files with file size from 1 to 31"
for i in {1..31}; do 
	$(./specific_byte_sizes $i > $i.txt);
	echo -n "."
done
for i in {1..15}; do
	$(./specific_byte_sizes $i > .hidden_$i.txt);
	echo -n "."
done
echo "Files with non-printing characters. Only 1 char sized files"
echo -ne '#include <stdio.h>\nint main(int ac, char *av[])\n{\nputchar(i);\nputchar("\\n");\nreturn(0);\n}\n' > b.c
gcc b.c -o non_print_chars
for i in {1..31}; do 
	$(./non_print_chars $i > non_printing-$i.txt);
	echo -n "."
done
echo "#########################"
echo "Wrong Permissions"
echo "#########################"
mkdir 0 100 200 300 400 500 600 700
for (( i=0;i<800;i+=100)); do
	pushd $i  >> /dev/null 2>&1
		echo "abcdefghijklmnopqrstuvwxyz" >> content.txt
		echo "abcdefghijklmnopqrstuvwxyz" >> ignored_content
	popd  >> /dev/null 2>&1
cp ignored_file perms_$i.txt
chmod $i $i perms_$i.txt
done

echo "#########################"
echo "No ownership and immutables"
echo "#########################"
echo "0123456789abcdef0123456789" >> immutable_file.txt
sudo chattr +i immutable_file.txt
echo "abcdefghijklmnopqrstuvwxyz" >> not_owner.txt
sudo chown root:root not_owner.txt


echo "#########################"
echo "Symlinks and Sockets"
echo "#########################"
touch tmp
ln -s tmp broken_symlink
rm tmp
python -c "import socket as s; k = s.socket(s.AF_UNIX); k.bind('socket_file')" 

popd  >> /dev/null 2>&1
